displayName=Lucky Penny Tracker
author=Aloza
description=A plugin to track gp saved by having Ghommal's Lucky Penny activated for your account.
tags=penny,tracker,gp,ghom,ghommal,lucky
version=1
plugins=com.luckypenny.GhommalLuckyPennyPlugin
build=standard
